version: '3.8'

networks:
  internal:

services:
  nginx:
    container_name: nginx
    image: nginx:1.25.2-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./web:/srv/test-task/web
    networks:
      - internal
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1001
    volumes:
      - ./:/srv/test-task
    networks:
      - internal